### ISSUE TITLE
Complete unit counter list (unique units)

### ISSUE THREAD

**Issue by denniske** [denniske/aoe2companion#10]
On the unit page there is a list with unit counters (weak vs. / strong vs.):

![image](https://user-images.githubusercontent.com/1076211/88915860-4e92e100-d265-11ea-932c-21689adbbd6c.png)

This list is missing **unique units**. The following resources can be used for reference:

Age of Empires 2 Visual Counter List 2.0
https://docs.google.com/spreadsheets/d/1XMFVhx-bJQJ3PbZEbJ4C4Bpw1CY5dKFiE6sr9MWpJME/edit#gid=0

Steam Counter List (section called "Aoe2 Unit Counter List")
https://steamcommunity.com/sharedfiles/filedetails/?id=860974959

To add unit counters edit/add `counteredBy` property in [units.ts](src/helper/units.ts).

Auto completion should work for that.
![image](https://user-images.githubusercontent.com/1076211/88916209-fa3c3100-d265-11ea-96ea-e2a0e55e5095.png)

**Comment by FifthSense** [comment]
Hi, Zamorak Haze from Discord here.
I have one main question and a set of subquestions:

Are the counteredBy Arrays supposed be **completed for Unique Units** or are Unique Units supposed be filled in in the counteredBy Array **for other units**? Or both?

- Is there any sort of hierarchy that should be followed in terms of order of notation (i.e.: non-unique units first, land units first,...)

- In regard to dock units, are land counters supposed to be given up as a counter? (i.e.: the mangonel line counters the fire line, but is not given up as a counter in it's counteredBy Array)

- I think the Excel Sheet contains some ambigious cases in terms of counters, how closely should it be mimicked?, I.e.:
1. The Battering Ram is considered a counter for Ballista Elephants. Imo that's a different type of counter than the traditional one, it's true Ballista Elephants don't deal a lot of damage against Rams, but Rams don't deal a lot of damage against Ballista Elephants either. So it's one of these cases where it could be annoying to have Rams destroying your buildings thus having to recruit other units, but it isn't really going to directly hurt your Elephants

2. This also works the other way, to stay with the Ballista Elephants, Spearmen are listed as a counter, but Ballista Elephants also deal a lot of damage to units with low pierce armor (such as the Spearman line), as a result, the spearmen most likely won't get close enough to deal damage

3. Mayan Plumed Archers are very rarely listed as a counter for anything even though they do basically counter everything that the archer-line counters. So you could say the creator of the spreadsheet assumes mentioning the archer line is sufficient, but the Chinese Chu-Ko-Nu is mentioned a few times as well. Same goed for Genitours and Skirms.

4. Monks and Scout Cav are very rarely listed

5. The Sheet notes that some things are only a counter when massed, how do i go about listing those cases?

6. Doesn't contain newer DE units

7. What with the Bulgarian Konnik? (their counters vary depending on them being mounted or not)

**Comment by denniske** [comment]
> Are the counteredBy Arrays supposed be completed for Unique Units or are Unique Units supposed be filled in in the counteredBy Array for other units? Or both?

Both

> Is there any sort of hierarchy that should be followed in terms of order of notation (i.e.: non-unique units first, land units first,...)

Yes this order sounds good. Feel free to also order the land units and other units like you think it makes sense.

> In regard to dock units, are land counters supposed to be given up as a counter? (i.e.: the mangonel line counters the fire line, but is not given up as a counter in it's counteredBy Array)

Yes I think they should be added. We can add a filter later where the user can show/hide land counters for dock units.

**Comment by FifthSense** [comment]
> > Is there any sort of hierarchy that should be followed in terms of order of notation (i.e.: non-unique units first, land units first,...)
> 
> Yes this order sounds good. Feel free to also order the land units and other units like you think it makes sense.

I've decided I'm going to order them in this way:
(Might be useful to save this somewhere in the documentation, this way some kind of uniform structure can be maintained when new units get added.)

Order of Notation Hierarchy - Counters:

1. Land Units > Water Units (<-> When the focussed unit is a water unit)
2. Non-Unique-Units > Unique-Units(incl. Eagles)
3. Ground Units > Mounted Units > Siege Units(incl. Petard)
4. Melee Units > Ranged Units(incl. monk/missionary) (<-> for water units)
5. Gold Units > Trash Units

I.E. With a counter list for a hypothetical Land Unit (Who presumably gets counterd by every type of unit):
(Land)(Non-Unique)(Ground)(Melee)(Gold unit) **Militia** ->
(Land)(Non-Unique)(Ground)(Melee)(Trash unit) **Spearman** ->  
(Land)(Non-Unique)(Ground)(Ranged)(Gold unit) **Archer** -> 
(Land)(Non-Unique)(Ground)(Ranged)(Gold unit) **Skirmisher** -> 
(Land)(Non-Unique)(Mounted)(Melee)(Gold Unit) **Knight** -> 
(Land)(Non-Unique)(Mounted)(Melee)(Trash Unit) **Scout Cav** -> 
(Land)(Non-Unique)(Mounted)(Ranged)(Gold Unit) **Cav Archer** -> 
(Land)(Non-Unique)(Siege)(Melee)(Gold Unit) **Battering Ram** -> 
(Land)(Non-Unique)(Siege)(Ranged)(Gold Unit) **Mangonel** -> 
(Land)(Unique Unit)(Ground)(Melee)(Gold Unit) **Samurai** -> 
(Land)(Unique Unit)(Ground)(Ranged)(Gold Unit) **Plumed Archer** -> 
(Land)(Unique Unit)(Mounted)(Melee)(Gold Unit) **War Elephant** -> 
(Land)(Unique Unit)(Mounted)(Ranged)(Gold Unit) **Mangudai** ->
(Water)(Non-Unique)(/)(Ranged)(Gold Unit) **Galley** ->
(Water)(Non-Unique)(/)(Melee)(Gold Unit) **Demo Raft** ->
(Water)(Unique Unit)(/)(Ranged)(Gold Unit) **Longboat** ->
(Water)(Unique Unit)(/)(Melee)(Gold Unit) **Turtle Ship**

**Comment by denniske** [comment]
Unit counters are quite complete. Closing this for now.
