### ISSUE TITLE
Tapping on push notification should send you to the mentioned game

### ISSUE THREAD

**Issue by SihingMo** [denniske/aoe2companion#20]
If you tap on a received push notification you expect to get to the mentioned game. Instead you switch to your profile.

**Comment by SihingMo** [comment]
Only happening if the app is closed at the time of the notification. If the app is open it switches to the following game list (although it would be cool if the mentioned game is already opened in the detailed manner)

**Comment by denniske** [comment]
This is already implemented but there is a bug in the framework.
The notification clicked event is not fired when app was closed at that time:
https://github.com/expo/expo/issues/6943

I will check this issue again when the framework bug is fixed.

**Comment by denniske** [comment]
I implemented a workaround in v14.0.14. Works on my android. Does it work on iOS?

**Comment by SihingMo** [comment]
Working on iOS.

**Comment by denniske** [comment]
Okay I will close this for now.
