### ISSUE TITLE
Real life time displayed instead of in-game time in Matches tab

### ISSUE THREAD

**Issue by spin0za** [denniske/aoe2companion#34]
Hi, I found this time information confusing, as it is real life time. Could you make it in-game time instead? Thanks! Also, is the duration under "Stats" tab in-game time? (where win rates of <5min, 5-30min, etc. are displayed)

![c9d770d90b6638e6265c35cc5baeb17](https://user-images.githubusercontent.com/5843313/110663359-3f422180-81be-11eb-9dbd-9f62f612cf02.png)

**Comment by spin0za** [comment]
Any plan to fix this? @denniske It should be trivial

**Comment by denniske** [comment]
Good catch! The stats already use ingame time. I have changed the display to ingame time in v26.0.4.
