### ISSUE TITLE
If you click on the Buy Me A Coffee link, the Windows App becomes unusable

### ISSUE THREAD

**Issue by SihingMo** [denniske/aoe2companion#36]
There is an issue with the Buy Me A Coffee link in the Windows App:
If you click on it, Buy Me a Coffee is opened inside the App and there is no possibility to switch back into the App. Only workaround is to close it and start it again. I would recommend to open the link in the system standard browser.

**Comment by denniske** [comment]
Fixed in v26.0.4+0
