### ISSUE TITLE
bug: navigate to incorrect civ page from a match

### ISSUE THREAD

**Issue by habaneraa** [denniske/aoe2companion#42]
Description: In a match detail, the app will navigate to an incorrect civilization page when clicking on a player's civ. For example, some player was Franks but it navigates to the page of Berbers.

Steps to reproduce:
- check match history of any player
- click to extend a match
- click the civ text of a player

Environment: I visit the web page (app.aoe2companion.com) by Edge browser in Android. 

screen recording:
<video src="https://user-images.githubusercontent.com/95517280/199543360-0f9d1aac-0ca0-4497-9d70-b79bd459b983.mp4
"></video>

**Comment by denniske** [comment]
Thanks for reporting. This occurred because Microsoft changed the order of the player ids. I think this should be fixed since some time.
