### ISSUE TITLE
Add screenshot to README.md

### ISSUE THREAD

**Issue by GantMan** [denniske/aoe2companion#5]
I'd love to see a few screenshots in the readme.

**Comment by denniske** [comment]
Good idea! I have added some screenshots. I will have to generate more up-to-date ones though. And maybe add the device frame to them. I will keep this issue open until this is completed.

**Comment by GantMan** [comment]
Awesome!

**Comment by denniske** [comment]
Finally added up-to-date screenshots with a nice grey border. Closing this issue.
