### ISSUE TITLE
bug: changing the leaderboard country doesn't refresh the top-101+ players

### ISSUE THREAD

**Issue by bryant1410** [denniske/aoe2companion#56]
In Android, if you set the leaderboard country to A, scroll and view the top 100-200, then change the country to B and navigate top the top 100-200, those players are from country A and not from B. Such players won't be refreshed, and the displayed list will be a mix.

**Comment by noahbrandyberry** [comment]
Found the issue and will release a fix in the next update. Thanks for reporting!
